/**
 * lib/db/database.types.ts
 *
 * Type definitions for the Supabase database schema.
 * Mirrors supabase/migrations/001_core_schema.sql exactly.
 *
 * Sprint 3: replace with types generated by `supabase gen types typescript`
 */

export type MovementType   = 'ingreso' | 'salida' | 'compra' | 'asignacion' | 'recuperacion' | 'baja';
export type AssetStatus    = 'Asignado' | 'Disponible' | 'Por Recuperar' | 'Defectuoso' | 'De Baja' | 'Reservado' | 'Stock / Nuevo';
export type AssetCondition = 'Nuevo' | 'Usado' | 'Defectuoso';
export type RiskLevel      = 'BAJO' | 'MEDIO' | 'ALTO' | 'CRÍTICO';
export type IngestionStatus= 'ok' | 'warning' | 'error';
export type PriorityLevel  = 'CRÍTICA' | 'ALTA' | 'MEDIA' | 'BAJA';
export type SnapshotType   = 'monthly' | 'manual' | 'incident' | 'annual';

// ─── Table row types ──────────────────────────────────────────

export interface BronzeIngestionLog {
  id:            string;
  batch_id:      string;
  source_file:   string;
  source_sheet:  string;
  load_timestamp:string;
  records_raw:   number;
  status:        IngestionStatus;
  error_message: string | null;
  metadata:      Record<string, unknown> | null;
}

export interface DimAsset {
  serial:               string;
  sku:                  string | null;
  tipo:                 string | null;
  marca:                string | null;
  modelo:               string | null;
  color:                string | null;
  anio_fabricacion:     number | null;
  cpu:                  string | null;
  ram:                  string | null;
  disco:                string | null;
  pantalla:             string | null;
  sistema_operativo:    string | null;
  estado:               AssetStatus | null;
  condicion:            AssetCondition | null;
  empleado:             string | null;
  rut_empleado:         string | null;
  cliente:              string | null;
  perfil:               string | null;
  ambito_laboral:       string | null;
  localizacion:         string | null;
  ciudad:               string | null;
  propiedad:            string | null;
  fecha_compra:         string | null;
  fecha_mantenimiento:  string | null;
  fecha_asignacion:     string | null;
  ciclos_bateria:       number | null;
  condicion_bateria:    string | null;
  valor_nuevo_usd:      number | null;
  valor_dep_usd:        number | null;
  dep_acumulada_usd:    number | null;
  pct_depreciado:       number | null;
  costo_renovacion_usd: number | null;
  risk_score:           number | null;
  risk_nivel:           RiskLevel | null;
  score_renovacion:     number | null;
  candidato_renovacion: boolean;
  calidad_dato:         number | null;
  fuente_hoja:          string | null;
  source_file:          string | null;
  load_timestamp:       string;
  updated_at:           string;
}

export interface FactMovement {
  movement_id:             string;
  tipo_movimiento:         MovementType;
  estado_resultante:       AssetStatus | null;
  fecha:                   string | null;
  fecha_retiro_confirmada: string | null;
  tiene_fecha:             boolean;
  empleado:                string | null;
  rut_empleado:            string | null;
  gestionado_por:          string | null;
  serial:                  string | null;
  modelo_raw:              string | null;
  cpu:                     string | null;
  ram:                     string | null;
  anio_fabricacion:        number | null;
  precio_referencia_usd:   number | null;
  tiene_serial:            boolean;
  cliente:                 string | null;
  ubicacion:               string | null;
  asset_cpu:               string | null;
  asset_anio:              number | null;
  asset_estado_actual:     AssetStatus | null;
  asset_risk_score:        number | null;
  asset_risk_nivel:        RiskLevel | null;
  asset_valor_dep:         number | null;
  fuente_hoja:             string;
  es_inferido:             boolean;
  riesgo_percibido_it:     RiskLevel | null;
  source_file:             string | null;
  load_timestamp:          string;
}

export interface FactAssetSnapshot {
  snapshot_date:      string;
  snapshot_type:      SnapshotType;
  serial:             string | null;
  estado:             AssetStatus | null;
  condicion:          AssetCondition | null;
  cliente:            string | null;
  area:               string | null;
  proyecto:           string | null;
  plataforma:         string | null;
  marca:              string | null;
  modelo:             string | null;
  anio_fabricacion:   number | null;
  ram:                string | null;
  disco:              string | null;
  empleado:           string | null;
  ciudad:             string | null;
  fuente:             string | null;
  valor_depreciado:   number | null;
  precio_nuevo:       number | null;
  costo_renovacion:   number | null;
  score_renovacion:   number | null;
  calidad_dato:       number | null;
  es_simulado:        boolean;
  load_timestamp:     string;
}

export interface GoldGovernanceSummary {
  snapshot_date:      string;
  quality_score:      number;
  quality_score_real: number;
  dg_score:           number;
  dg_level:           number;
  dg_level_label:     string;
  total_movements:    number;
  real_movements:     number;
  inferred_movements: number;
  records_to_fix:     number;
  main_gap:           string | null;
  secondary_gap:      string | null;
  computed_at:        string;
}

export interface GoldCompletenessKpi {
  snapshot_date:  string;
  field_name:     string;
  field_label:    string;
  pct_complete:   number;
  count_ok:       number;
  count_total:    number;
  semaphore:      string;
  note:           string | null;
  is_strategic:   boolean;
  computed_at:    string;
}

export interface GoldGapBySource {
  snapshot_date:   string;
  source_name:     string;
  source_short:    string;
  total_records:   number;
  missing_serial:  number;
  missing_date:    number;
  missing_client:  number;
  missing_manager: number;
  is_inferred:     boolean;
  pct_serial:      number;
  pct_date:        number;
  priority:        PriorityLevel;
  action_text:     string | null;
  computed_at:     string;
}

export interface GoldRecordToFix {
  snapshot_date: string;
  movement_id:   string;
  tipo:          string | null;
  employee:      string | null;
  serial:        string | null;
  fecha:         string | null;
  client:        string | null;
  manager:       string | null;
  source:        string | null;
  issue_count:   number;
  issues:        string[];
  computed_at:   string;
}

export interface GoldQualityTrend {
  snapshot_date: string;
  park_quality:  number;
  dg_score:      number | null;
  total_assets:  number;
  is_simulated:  boolean;
  computed_at:   string;
}

export interface GoldQualityComponent {
  snapshot_date: string;
  component:     string;
  weight:        number;
  score:         number;
  contribution:  number;
  computed_at:   string;
}

export interface CfgBronzeSource {
  id:             number;
  name:           string;
  source_type:    string;
  sheet_name:     string;
  last_load_date: string | null;
  status:         IngestionStatus;
  records_count:  number;
  missing_serial: number;
  missing_date:   number;
  updated_at:     string;
}

export interface CfgSilverRule {
  id:            number;
  field_name:    string;
  function_name: string;
  description:   string;
}

export interface CfgGoldMart {
  id:             string;
  name:           string;
  description:    string;
  status:         'operational' | 'partial' | 'designed';
  source_desc:    string;
  business_value: string;
  record_count:   number | null;
  last_updated:   string | null;
  updated_at:     string;
}

export interface CfgChecklistStep {
  id:               number;
  phase:            string;
  step_code:        string;
  task:             string;
  description:      string;
  responsible:      string;
  time_estimate:    string;
  success_criteria: string;
  sort_order:       number;
}

export interface CfgOperationRule {
  id:              number;
  movement_type:   string;
  icon:            string;
  when_to_record:  string;
  required_fields: string;
  deadline:        string;
  common_error:    string;
}

export interface CfgTemplateField {
  id:           number;
  field_name:   string;
  required:     boolean;
  input_type:   string;
  valid_values: string;
  description:  string;
  is_ml_target: boolean;
  sort_order:   number;
}

// ─── Supabase Database interface ──────────────────────────────
export interface Database {
  public: {
    Tables: {
      bronze_ingestion_log:   { Row: BronzeIngestionLog; Insert: Omit<BronzeIngestionLog, 'id' | 'load_timestamp'>; Update: Partial<BronzeIngestionLog> };
      dim_asset:              { Row: DimAsset; Insert: Omit<DimAsset, 'load_timestamp' | 'updated_at'>; Update: Partial<DimAsset> };
      fact_movements:         { Row: FactMovement; Insert: Omit<FactMovement, 'load_timestamp'>; Update: Partial<FactMovement> };
      fact_asset_snapshot:    { Row: FactAssetSnapshot; Insert: Omit<FactAssetSnapshot, 'load_timestamp'>; Update: Partial<FactAssetSnapshot> };
      gold_governance_summary:{ Row: GoldGovernanceSummary; Insert: Omit<GoldGovernanceSummary, 'computed_at'>; Update: Partial<GoldGovernanceSummary> };
      gold_completeness_kpis: { Row: GoldCompletenessKpi; Insert: Omit<GoldCompletenessKpi, 'computed_at'>; Update: Partial<GoldCompletenessKpi> };
      gold_gaps_by_source:    { Row: GoldGapBySource; Insert: Omit<GoldGapBySource, 'computed_at'>; Update: Partial<GoldGapBySource> };
      gold_records_to_fix:    { Row: GoldRecordToFix; Insert: Omit<GoldRecordToFix, 'computed_at'>; Update: Partial<GoldRecordToFix> };
      gold_quality_trend:     { Row: GoldQualityTrend; Insert: Omit<GoldQualityTrend, 'computed_at'>; Update: Partial<GoldQualityTrend> };
      gold_quality_components:{ Row: GoldQualityComponent; Insert: Omit<GoldQualityComponent, 'computed_at'>; Update: Partial<GoldQualityComponent> };
      cfg_bronze_sources:     { Row: CfgBronzeSource; Insert: Omit<CfgBronzeSource, 'id' | 'updated_at'>; Update: Partial<CfgBronzeSource> };
      cfg_silver_rules:       { Row: CfgSilverRule; Insert: Omit<CfgSilverRule, 'id'>; Update: Partial<CfgSilverRule> };
      cfg_gold_marts:         { Row: CfgGoldMart; Insert: Omit<CfgGoldMart, 'updated_at'>; Update: Partial<CfgGoldMart> };
      cfg_checklist_steps:    { Row: CfgChecklistStep; Insert: Omit<CfgChecklistStep, 'id'>; Update: Partial<CfgChecklistStep> };
      cfg_operation_rules:    { Row: CfgOperationRule; Insert: Omit<CfgOperationRule, 'id'>; Update: Partial<CfgOperationRule> };
      cfg_template_fields:    { Row: CfgTemplateField; Insert: Omit<CfgTemplateField, 'id'>; Update: Partial<CfgTemplateField> };
    };
    Views: {
      v_governance_summary:  { Row: GoldGovernanceSummary };
      v_completeness_kpis:   { Row: GoldCompletenessKpi };
      v_gaps_by_source:      { Row: GoldGapBySource };
      v_records_to_fix:      { Row: GoldRecordToFix };
      v_quality_trend:       { Row: GoldQualityTrend };
      v_quality_components:  { Row: GoldQualityComponent };
    };
    Functions: {
      fn_compute_governance_summary: { Args: { p_snapshot_date: string }; Returns: void };
    };
  };
}
