-- ============================================================
-- Migration 001 — Core schema
-- 2Brains Asset Governance Platform · Sprint 2
-- Medallion architecture: Bronze → Silver → Gold
-- ============================================================

-- ── Extensions ───────────────────────────────────────────────
create extension if not exists "pgcrypto";

-- ── Enums ────────────────────────────────────────────────────
create type movement_type as enum (
  'ingreso', 'salida', 'compra', 'asignacion', 'recuperacion', 'baja'
);

create type asset_status as enum (
  'Asignado', 'Disponible', 'Por Recuperar', 'Defectuoso', 'De Baja', 'Reservado', 'Stock / Nuevo'
);

create type asset_condition as enum (
  'Nuevo', 'Usado', 'Defectuoso'
);

create type risk_level as enum (
  'BAJO', 'MEDIO', 'ALTO', 'CRÍTICO'
);

create type ingestion_status as enum (
  'ok', 'warning', 'error'
);

create type priority_level as enum (
  'CRÍTICA', 'ALTA', 'MEDIA', 'BAJA'
);

-- ── BRONZE — Raw ingestion log ────────────────────────────────
-- Every xlsx load produces one row per sheet processed.
-- Records are append-only and immutable.
create table bronze_ingestion_log (
  id               uuid        primary key default gen_random_uuid(),
  batch_id         uuid        not null,
  source_file      text        not null,
  source_sheet     text        not null,
  load_timestamp   timestamptz not null default now(),
  records_raw      integer     not null,
  status           ingestion_status not null default 'ok',
  error_message    text,
  metadata         jsonb       -- arbitrary key-value from the source
);

create index bronze_ingestion_log_batch_id  on bronze_ingestion_log(batch_id);
create index bronze_ingestion_log_timestamp on bronze_ingestion_log(load_timestamp desc);

-- ── SILVER — dim_asset ────────────────────────────────────────
-- Normalised master record for every physical asset.
-- Upsert on serial. Enriched by Silver pipeline from Bronze.
create table dim_asset (
  -- Identity
  serial               text        primary key,
  sku                  text,
  tipo                 text,
  marca                text,
  modelo               text,
  color                text,
  anio_fabricacion     smallint,

  -- Hardware
  cpu                  text,
  ram                  text,
  disco                text,
  pantalla             text,
  sistema_operativo    text,

  -- Estado
  estado               asset_status,
  condicion            asset_condition,

  -- Asignación
  empleado             text,
  rut_empleado         text,
  cliente              text,
  perfil               text,
  ambito_laboral       text,
  localizacion         text,
  ciudad               text,
  propiedad            text,

  -- Fechas
  fecha_compra         date,
  fecha_mantenimiento  date,
  fecha_asignacion     date,

  -- Batería
  ciclos_bateria       integer,
  condicion_bateria    text,

  -- Financiero (computed by Silver pipeline)
  valor_nuevo_usd      numeric(10,2),
  valor_dep_usd        numeric(10,2),
  dep_acumulada_usd    numeric(10,2),
  pct_depreciado       numeric(5,1),
  costo_renovacion_usd numeric(10,2),

  -- Risk & Quality (computed by Silver pipeline)
  risk_score           smallint    check (risk_score between 0 and 100),
  risk_nivel           risk_level,
  score_renovacion     smallint    check (score_renovacion between 0 and 100),
  candidato_renovacion boolean     not null default false,
  calidad_dato         smallint    check (calidad_dato between 0 and 100),

  -- Traceability (Bronze fields carried forward)
  fuente_hoja          text,
  source_file          text,
  load_timestamp       timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index dim_asset_estado   on dim_asset(estado);
create index dim_asset_cliente  on dim_asset(cliente);
create index dim_asset_riesgo   on dim_asset(risk_nivel);
create index dim_asset_updated  on dim_asset(updated_at desc);

-- Auto-update updated_at
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger dim_asset_updated_at
  before update on dim_asset
  for each row execute function set_updated_at();

-- ── SILVER — fact_movements ───────────────────────────────────
-- Every discrete event on an asset. Append-only.
-- movement_id is generated by the Silver pipeline (MD5 of type+date+employee+serial).
create table fact_movements (
  movement_id          text        primary key,
  tipo_movimiento      movement_type not null,
  estado_resultante    asset_status,

  -- Temporal
  fecha                date,
  fecha_retiro_confirmada date,
  tiene_fecha          boolean     not null default false,

  -- Person
  empleado             text,
  rut_empleado         text,
  gestionado_por       text,

  -- Asset link
  serial               text        references dim_asset(serial) on delete set null,
  modelo_raw           text,
  cpu                  text,
  ram                  text,
  anio_fabricacion     smallint,
  precio_referencia_usd numeric(10,2),
  tiene_serial         boolean     not null default false,

  -- Business
  cliente              text,
  ubicacion            text,

  -- Enriched from dim_asset at ingest time
  asset_cpu            text,
  asset_anio           smallint,
  asset_estado_actual  asset_status,
  asset_risk_score     smallint,
  asset_risk_nivel     risk_level,
  asset_valor_dep      numeric(10,2),

  -- Quality flags
  fuente_hoja          text        not null,
  es_inferido          boolean     not null default false,

  -- ML target (to be filled by IT team)
  riesgo_percibido_it  risk_level,

  -- Traceability
  source_file          text,
  load_timestamp       timestamptz not null default now()
);

create index fact_movements_serial      on fact_movements(serial);
create index fact_movements_fecha       on fact_movements(fecha);
create index fact_movements_tipo        on fact_movements(tipo_movimiento);
create index fact_movements_cliente     on fact_movements(cliente);
create index fact_movements_fuente      on fact_movements(fuente_hoja);
create index fact_movements_inferido    on fact_movements(es_inferido);

-- ── GOLD — fact_asset_snapshot ────────────────────────────────
-- Monthly / manual / incident / annual park photographs.
-- PK: (snapshot_date, serial).
create type snapshot_type as enum ('monthly', 'manual', 'incident', 'annual');

create table fact_asset_snapshot (
  snapshot_date        date        not null,
  snapshot_type        snapshot_type not null default 'monthly',
  serial               text,       -- nullable: assets without serial still counted
  estado               asset_status,
  condicion            asset_condition,
  cliente              text,
  area                 text,
  proyecto             text,
  plataforma           text,       -- normalised CPU family
  marca                text,
  modelo               text,
  anio_fabricacion     smallint,
  ram                  text,
  disco                text,
  empleado             text,
  ciudad               text,
  fuente               text,
  valor_depreciado     numeric(10,2),
  precio_nuevo         numeric(10,2),
  costo_renovacion     numeric(10,2),
  score_renovacion     smallint,
  calidad_dato         smallint,
  es_simulado          boolean     not null default false,
  load_timestamp       timestamptz not null default now(),

  primary key (snapshot_date, coalesce(serial, 'NO_SERIAL_' || load_timestamp::text))
);

create index fact_asset_snapshot_date   on fact_asset_snapshot(snapshot_date desc);
create index fact_asset_snapshot_serial on fact_asset_snapshot(serial);
create index fact_asset_snapshot_estado on fact_asset_snapshot(estado);
create index fact_asset_snapshot_cliente on fact_asset_snapshot(cliente);

-- ── GOLD — gold_governance_summary ───────────────────────────
-- Computed governance metrics per snapshot date.
-- Recalculated after every Silver pipeline run.
create table gold_governance_summary (
  snapshot_date         date        primary key,
  quality_score         numeric(5,1) not null,
  quality_score_real    numeric(5,1) not null,
  dg_score              numeric(5,1) not null,
  dg_level              smallint    not null check (dg_level between 1 and 5),
  dg_level_label        text        not null,
  total_movements       integer     not null,
  real_movements        integer     not null,
  inferred_movements    integer     not null,
  records_to_fix        integer     not null,
  main_gap              text,
  secondary_gap         text,
  computed_at           timestamptz not null default now()
);

-- ── GOLD — gold_completeness_kpis ────────────────────────────
-- Per-field completeness metrics per snapshot date.
create table gold_completeness_kpis (
  snapshot_date   date        not null,
  field_name      text        not null,
  field_label     text        not null,
  pct_complete    numeric(5,1) not null,
  count_ok        integer     not null,
  count_total     integer     not null,
  semaphore       text        not null check (semaphore in ('green','yellow','orange','red')),
  note            text,
  is_strategic    boolean     not null default false,
  computed_at     timestamptz not null default now(),
  primary key (snapshot_date, field_name)
);

-- ── GOLD — gold_gaps_by_source ───────────────────────────────
create table gold_gaps_by_source (
  snapshot_date     date        not null,
  source_name       text        not null,
  source_short      text        not null,
  total_records     integer     not null,
  missing_serial    integer     not null default 0,
  missing_date      integer     not null default 0,
  missing_client    integer     not null default 0,
  missing_manager   integer     not null default 0,
  is_inferred       boolean     not null default false,
  pct_serial        numeric(5,1) not null,
  pct_date          numeric(5,1) not null,
  priority          priority_level not null,
  action_text       text,
  computed_at       timestamptz not null default now(),
  primary key (snapshot_date, source_name)
);

-- ── GOLD — gold_records_to_fix ────────────────────────────────
create table gold_records_to_fix (
  snapshot_date   date        not null,
  movement_id     text        not null,
  tipo            text,
  employee        text,
  serial          text,
  fecha           date,
  client          text,
  manager         text,
  source          text,
  issue_count     smallint    not null,
  issues          text[]      not null,  -- e.g. '{sin_serial,sin_fecha}'
  computed_at     timestamptz not null default now(),
  primary key (snapshot_date, movement_id)
);

-- ── GOLD — gold_quality_trend ─────────────────────────────────
create table gold_quality_trend (
  snapshot_date    date        primary key,
  park_quality     numeric(5,1) not null,
  dg_score         numeric(5,1),
  total_assets     integer     not null,
  is_simulated     boolean     not null default false,
  computed_at      timestamptz not null default now()
);

-- ── GOLD — gold_quality_components ───────────────────────────
create table gold_quality_components (
  snapshot_date   date        not null,
  component       text        not null,
  weight          numeric(4,2) not null,
  score           numeric(5,1) not null,
  contribution    numeric(5,1) not null,
  computed_at     timestamptz not null default now(),
  primary key (snapshot_date, component)
);

-- ── Static config tables (reference data) ─────────────────────
-- These rarely change; seeded once and read by services.

create table cfg_bronze_sources (
  id              serial      primary key,
  name            text        not null unique,
  source_type     text        not null default 'Excel sheet',
  sheet_name      text        not null,
  last_load_date  date,
  status          ingestion_status not null default 'ok',
  records_count   integer     not null default 0,
  missing_serial  integer     not null default 0,
  missing_date    integer     not null default 0,
  updated_at      timestamptz not null default now()
);

create table cfg_silver_rules (
  id              serial      primary key,
  field_name      text        not null unique,
  function_name   text        not null,
  description     text        not null
);

create table cfg_gold_marts (
  id              text        primary key,
  name            text        not null,
  description     text        not null,
  status          text        not null check (status in ('operational','partial','designed')),
  source_desc     text        not null,
  business_value  text        not null,
  record_count    integer,
  last_updated    date,
  updated_at      timestamptz not null default now()
);

create table cfg_checklist_steps (
  id              serial      primary key,
  phase           text        not null,
  step_code       text        not null unique,
  task            text        not null,
  description     text        not null,
  responsible     text        not null,
  time_estimate   text        not null,
  success_criteria text       not null,
  sort_order      smallint    not null
);

create table cfg_operation_rules (
  id              serial      primary key,
  movement_type   text        not null unique,
  icon            text        not null,
  when_to_record  text        not null,
  required_fields text        not null,
  deadline        text        not null,
  common_error    text        not null
);

create table cfg_template_fields (
  id              serial      primary key,
  field_name      text        not null unique,
  required        boolean     not null default true,
  input_type      text        not null,
  valid_values    text        not null,
  description     text        not null,
  is_ml_target    boolean     not null default false,
  sort_order      smallint    not null
);
